import type { Metadata } from "next";
import { Source_Sans_3, Noto_Sans_Arabic, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RouteProgressBar } from "@/components/ui/route-progress";

const appSans = Source_Sans_3({
  variable: "--font-app-sans",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  display: "swap",
});

const arabicSans = Noto_Sans_Arabic({
  variable: "--font-arabic-sans",
  subsets: ["arabic"],
  weight: ["400","500","600","700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400","500","600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
  <body className={`${appSans.variable} ${arabicSans.variable} ${geistMono.variable} antialiased font-sans`} suppressHydrationWarning>
  <RouteProgressBar />
  {children}
      </body>
    </html>
  );
}
